### ISSUE TITLE
No resolver defined for scheme 'file' in ref

### ISSUE THREAD

**Issue by anteprimorac** [tillig/vscode-spectral#5]
Keep getting this error only in vscode that seems related to this extension.

```json
{
	"range": {
		"start": {
			"line": 89,
			"character": 36
		},
		"end": {
			"line": 89,
			"character": 63
		}
	},
	"severity": 1,
	"code": "invalid-ref",
	"source": "spectral",
	"message": "No resolver defined for scheme 'file' in ref ../models/partner.v1.json"
}
```

Let me know if you need more info about this.

**Comment by tillig** [comment]
A small repro would be helpful. If I can't repro/debug it, I can't fix it.

**Comment by sebas2day** [comment]
I believe I'm having similar issues:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/5485197/78678735-a63dc300-78e9-11ea-8f32-f8b7d6adead6.png">

Could it be of not having the default `@stoplight/json-ref-resolver` package included? 

It would be nice to have the ability to specify a custom resolver in the config like you can in the [docs](https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/guides/javascript.md?srn=gh/stoplightio/spectral/docs/guides/javascript.md#using-custom-resolver). But just having the default would be sufficient for me :)

**Comment by tillig** [comment]
Again, a small repro would really help me out. Screen shots are nice to see the error message, but to debug it _I really need that repro_ even if you just paste some JSON right here in the issue.

**Comment by tillig** [comment]
(Which is to say, I need something that validates correctly with command line Spectral but fails in the VS Code add-in so I can see what's working/what's not and fix it.)

**Comment by anteprimorac** [comment]
Let me know if this helps https://github.com/anteprimorac/vscode-spectral-no-resolver

**Comment by tillig** [comment]
Yeah! Awesome. Let me see what I can do.

**Comment by tillig** [comment]
OK, I figured it out. I'll get a v1.2.0 out with this fix shortly. (Includes an update to Spectral 5.3.0.)

**Comment by anteprimorac** [comment]
@tillig thanks for this, but I am experiencing another problem. It seems like it's encoding whitespaces to `%20` and if you have them in your file path, it can't resolve it.

Example of error:
`ENOENT: no such file or directory, open '/Users/ante/Documents/Stoplight%20Studio/vscode-spectral-no-resolver/models/model.v1.json'`

**Comment by tillig** [comment]
OK, that wasn't in the repro. I'm going to create a new issue for this since it's a new error, not the same one. We have a resolver for `file`, now there's a path encoding issue.

**Comment by anteprimorac** [comment]
@tillig I agree, thanks for creating a new issue.
